# Generated by Django 4.0.4 on 2022-04-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_showlist_tvlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('prem_date', models.DateField()),
                ('country_origin', models.CharField(max_length=250)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tvlist')),
            ],
        ),
    ]
