# Generated by Django 4.0.4 on 2022-04-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_studio_name_alter_studio_prem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='show',
            new_name='tv',
        ),
    ]
