# Generated by Django 4.0.4 on 2022-04-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tvplatform_tvlist_tv_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=250)),
                ('host_type', models.CharField(choices=[('Web', 'Web Platform'), ('Cable', 'Cable Television')], default='Web', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvlist',
            name='tv_platforms',
        ),
        migrations.DeleteModel(
            name='TvPlatform',
        ),
        migrations.AddField(
            model_name='tvlist',
            name='tv_hosts',
            field=models.ManyToManyField(to='main_app.tvhost'),
        ),
    ]
