# Generated by Django 4.0.4 on 2022-04-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tvhost_remove_tvlist_tv_platforms_delete_tvplatform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvhost',
            old_name='host_name',
            new_name='name',
        ),
    ]
